### ISSUE TITLE
Battery reporting does not work with newer versions of BlueZ

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/libasteroid#13]
Starting with BlueZ version 5.56, it has implemented the Battery1 service.
https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=9e2fd160e119d6d3e2d8f37b254b7e72c502d437

I think that because BlueZ is now handling this characteristic, libasteroid no longer gets the message and always reports 0% instead.

**Comment by beroset** [comment]
I have verified that a change to BlueZ is the cause.   With no modifications to any other software I installed version 5.55 where the battery display was always 0% and then backed up to version 5.54 and it started working.  So the change was even earlier than I had thought, but I'm still working to identify exactly which change caused the change in behavior.

**Comment by beroset** [comment]
I have figured out that it was this patch that caused the change in behavior: https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=713f6f09
What the patch purports to do is to allow an exception so that the Battery1 profile and the GATT API can safely both report.  However, the sense seems to be somehow inverted.  The patch contains these lines:
```
diff --git a/[profiles/battery/battery.c](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/profiles/battery/battery.c?id=d5e07945c4aa36a83addc3c269f55c720c28afdb) b/[profiles/battery/battery.c](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/profiles/battery/battery.c?id=713f6f09f017abfccc2da9dbf2b32adf9ecb8e58)
index 4da4355a1..c9a1af4b9 100644
--- a/profiles/battery/battery.c
+++ b/profiles/battery/battery.c
@@ -354,6 +354,7 @@ static struct btd_profile batt_profile = {
 	.device_remove	= batt_remove,
 	.accept		= batt_accept,
 	.disconnect	= batt_disconnect,
+	.external	= true,
 };
 
 static int batt_init(void)
```
However, I find that things work again as expected if I invert the value of `.external`.

**Comment by beroset** [comment]
More investigations show that the chronology is something like this:
 1. everything was working at one point
 2. BlueZ changed to implement the Battery1 interface
 3. Qt changed to check for existence of Battery1 interface and compensate with "artificial" GATT characteristic (see https://bugreports.qt.io/browse/QTBUG-70222 )
 4. BlueZ changed again to allow non-exclusive use of Battery1 interface (the patch mentioned in the previous comment)
 
I think that this dance between the two code bases explains the symptoms we're seeing, so the next step is to alter the Qt `qtconnectivity` code to test this theory.

**Comment by beroset** [comment]
Added a comment on Qt Bug 70222:  https://bugreports.qt.io/browse/QTBUG-70222?focusedCommentId=653952&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-653952

**Comment by beroset** [comment]
Fixed in the Qt sources:  https://bugreports.qt.io/browse/QTBUG-70222

**Comment by MagneFire** [comment]
Awesome work with this!
Very impressed by the wide range of BlueZ versions you verified against :+1:
